name: Publish ais-k8s release 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

env:
  AISOPERATOR_IMAGE: 'aistorage/ais-operator'
  VERSION: ${{ github.event.inputs.version }}

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v2

    - uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'
  
    - name: Make operator yaml file and helm chart
      run: |
        pushd $GITHUB_WORKSPACE/operator
        VERSION="${{ env.VERSION }}" IMG="${{ env.AISOPERATOR_IMAGE }}:${{ env.VERSION }}" make build-installer-helm
        popd

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: operator/dist/*
        tag_name: ${{ env.VERSION }}
        generate_release_notes: true
