name: Publish ais-k8s release
  on:
    push:
      tags:
        - 'v*'

env:
  AISOPERATOR_IMAGE: 'aistorage/ais-operator'
  VERSION: ${{ inputs.version }}

jobs:
  release:
    runs-on: self-hosted
    steps:
    
    - name: Checkout Repo
      uses: actions/checkout@v2
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.22.0'

    - name: Make aisoperator image
      run: |
        pushd $GITHUB_WORKSPACE/operator
        IMG="${{ env.AISOPERATOR_IMAGE }}:${{ env.VERSION }}" make docker-build
        popd
  
    - name: Make operator manifest and helm chart
      run: |
        pushd $GITHUB_WORKSPACE/operator
        VERSION="${{ env.VERSION }}" IMG="${{ env.AISOPERATOR_IMAGE }}:${{ env.VERSION }}" make helm-chart
        popd

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: operator/dist/*
